ifeq ($(TARGET_USES_QMAA),true)
     ifdef TARGET_USES_QMAA_OVERRIDE_HSI2S
     ifeq ($(TARGET_USES_QMAA_OVERRIDE_HSI2S),true)
              PRODUCT_PACKAGES += hsi2s.ko
     endif #TARGET_USES_QMAA_OVERRIDE_HSI2S
     endif
endif #TARGET_USES_QMAA
