# Build HSI2S kernel driver
ifneq ($(TARGET_DISABLE_HSI2S_DLKM) ,true)
$(warning TARGET_DISABLE_HSI2S_DLKM=$(TARGET_DISABLE_HSI2S_DLKM))

INCLUDE_KO_FILES := true
ifeq ($(TARGET_USES_QMAA),true)
$(warning TARGET_USES_QMAA=$(TARGET_USES_QMAA))
     ifdef TARGET_USES_QMAA_OVERRIDE_HSI2S
$(warning TARGET_USES_QMAA_OVERRIDE_HSI2S=$(TARGET_USES_QMAA_OVERRIDE_HSI2S))
     ifneq ($(TARGET_USES_QMAA_OVERRIDE_HSI2S),true)
         ifeq ($(TARGET_BOARD_AUTO), true)
$(warning TARGET_BOARD_AUTO=$(TARGET_BOARD_AUTO))
	      INCLUDE_KO_FILES := false
          endif #TARGET_BOARD_AUTO
     endif #TARGET_USES_QMAA_OVERRIDE_HSI2S
     endif
endif #TARGET_USES_QMAA
$(warning INCLUDE_KO_FILES=$(INCLUDE_KO_FILES))
ifeq ($(INCLUDE_KO_FILES),true)
	BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/hsi2s.ko
endif #INCLUDE_KO_FILES
endif #TARGET_DISABLE_HSI2S_DLKM