# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2021, The Linux Foundation. All rights reserved.

ifeq (y, $(findstring y, $(CONFIG_QTI_QUIN_GVM)))
ifeq ($(CONFIG_QGKI), y)
export CONFIG_HSI2S=m
endif
else
export CONFIG_HSI2S=m
endif
